  # ------------------------------------------------------------
  # Web Server
  # ------------------------------------------------------------
  chainhost1:
    image: blockchain
    restart: "no"

    ports:
      # ---- Format: ----
      - "81:5000"

    networks:
      app_net:
        ipv4_address: 172.16.238.11


################################################################################
# NETWORK
################################################################################
networks:
  app_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 179.20.238.0/24
          gateway: 179.20.238.1